DROP DATABASE IF EXISTS `sunwood`;

CREATE DATABASE `sunwood` DEFAULT CHARACTER SET utf8;

GRANT SELECT,INSERT,UPDATE,DELETE
ON `sunwood`.*
TO user@localhost
IDENTIFIED BY 'user';

GRANT SELECT,INSERT,UPDATE,DELETE
ON `sunwood`.*
TO user@'%'
IDENTIFIED BY 'user';
